/*
 * This file is generated by jOOQ.
 */
package com.github.wlmx.jooq.public_;


import com.github.wlmx.jooq.public_.tables.Test;
import com.github.wlmx.jooq.public_.tables.Test_2;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.TEST</code>.
     */
    public static final Test TEST = Test.TEST;

    /**
     * The table <code>PUBLIC.TEST_2</code>.
     */
    public static final Test_2 TEST_2 = Test_2.TEST_2;
}
